apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unsealer
subjects:
- kind: ServiceAccount
  name: vault-unsealer
roleRef:
  kind: Role
  name: vault-unsealer
  apiGroup: rbac.authorization.k8s.io
